spring:
  application:
    name: "configserver"
  profiles:
   # active: native
   active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///C:/workspace/microservices/section6/document/section6/config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "wmeklg56656556ln554klka4757klawfwqefnqwli6484"

server:
  port: 8071
